name = "jarvai-landing"
compatibility_date = "2024-01-01"

[env.production]
name = "jarvai-landing"

[[pages_builds]]
command = "npm run build"
cwd = "."
watch_dir = "."

[build]
command = "npm run build"
cwd = "."
